// AUTO-GENERATED by scripts/build-mob-library.mjs — do not edit by hand.
// Rebuild with: pnpm build:mobs "<path to capture/run/entity-capture>"

export type MobCategory = "passive" | "water" | "hostile";

export interface BuiltinMob {
  /** Namespaced entity id, e.g. `minecraft:zombie`. */
  id: string;
  /** Localized display name baked in at capture time. */
  name: string;
  category: MobCategory;
  /** File name under `public/mobs/`. */
  file: string;
}

export const BUILTIN_MOBS: BuiltinMob[] = [
  { id: "minecraft:ocelot", name: "豹猫", category: "passive", file: "ocelot.mcvox" },
  { id: "minecraft:polar_bear", name: "北极熊", category: "passive", file: "polar_bear.mcvox" },
  { id: "minecraft:bat", name: "蝙蝠", category: "passive", file: "bat.mcvox" },
  { id: "minecraft:strider", name: "炽足兽", category: "passive", file: "strider.mcvox" },
  { id: "minecraft:villager", name: "村民", category: "passive", file: "villager.mcvox" },
  { id: "minecraft:wither", name: "凋灵", category: "hostile", file: "wither.mcvox" },
  { id: "minecraft:wither_skeleton", name: "凋灵骷髅", category: "hostile", file: "wither_skeleton.mcvox" },
  { id: "minecraft:cave_spider", name: "洞穴蜘蛛", category: "hostile", file: "cave_spider.mcvox" },
  { id: "minecraft:silverfish", name: "蠹虫", category: "hostile", file: "silverfish.mcvox" },
  { id: "minecraft:ghast", name: "恶魂", category: "hostile", file: "ghast.mcvox" },
  { id: "minecraft:glow_squid", name: "发光鱿鱼", category: "water", file: "glow_squid.mcvox" },
  { id: "minecraft:salmon", name: "鲑鱼", category: "water", file: "salmon.mcvox" },
  { id: "minecraft:turtle", name: "海龟", category: "passive", file: "turtle.mcvox" },
  { id: "minecraft:dolphin", name: "海豚", category: "water", file: "dolphin.mcvox" },
  { id: "minecraft:pufferfish", name: "河豚", category: "water", file: "pufferfish.mcvox" },
  { id: "minecraft:fox", name: "狐狸", category: "passive", file: "fox.mcvox" },
  { id: "minecraft:illusioner", name: "幻术师", category: "hostile", file: "illusioner.mcvox" },
  { id: "minecraft:phantom", name: "幻翼", category: "hostile", file: "phantom.mcvox" },
  { id: "minecraft:evoker", name: "唤魔者", category: "hostile", file: "evoker.mcvox" },
  { id: "minecraft:chicken", name: "鸡", category: "passive", file: "chicken.mcvox" },
  { id: "minecraft:warden", name: "监守者", category: "hostile", file: "warden.mcvox" },
  { id: "minecraft:zombie", name: "僵尸", category: "hostile", file: "zombie.mcvox" },
  { id: "minecraft:zombie_villager", name: "僵尸村民", category: "hostile", file: "zombie_villager.mcvox" },
  { id: "minecraft:zombie_horse", name: "僵尸马", category: "passive", file: "zombie_horse.mcvox" },
  { id: "minecraft:zoglin", name: "僵尸疣猪兽", category: "hostile", file: "zoglin.mcvox" },
  { id: "minecraft:zombified_piglin", name: "僵尸猪灵", category: "hostile", file: "zombified_piglin.mcvox" },
  { id: "minecraft:ravager", name: "劫掠兽", category: "hostile", file: "ravager.mcvox" },
  { id: "minecraft:giant", name: "巨人", category: "hostile", file: "giant.mcvox" },
  { id: "minecraft:tadpole", name: "蝌蚪", category: "passive", file: "tadpole.mcvox" },
  { id: "minecraft:skeleton", name: "骷髅", category: "hostile", file: "skeleton.mcvox" },
  { id: "minecraft:skeleton_horse", name: "骷髅马", category: "passive", file: "skeleton_horse.mcvox" },
  { id: "minecraft:creeper", name: "苦力怕", category: "hostile", file: "creeper.mcvox" },
  { id: "minecraft:wolf", name: "狼", category: "passive", file: "wolf.mcvox" },
  { id: "minecraft:blaze", name: "烈焰人", category: "hostile", file: "blaze.mcvox" },
  { id: "minecraft:wandering_trader", name: "流浪商人", category: "passive", file: "wandering_trader.mcvox" },
  { id: "minecraft:stray", name: "流浪者", category: "hostile", file: "stray.mcvox" },
  { id: "minecraft:donkey", name: "驴", category: "passive", file: "donkey.mcvox" },
  { id: "minecraft:pillager", name: "掠夺者", category: "hostile", file: "pillager.mcvox" },
  { id: "minecraft:mule", name: "骡", category: "passive", file: "mule.mcvox" },
  { id: "minecraft:camel", name: "骆驼", category: "passive", file: "camel.mcvox" },
  { id: "minecraft:horse", name: "马", category: "passive", file: "horse.mcvox" },
  { id: "minecraft:cat", name: "猫", category: "passive", file: "cat.mcvox" },
  { id: "minecraft:axolotl", name: "美西螈", category: "passive", file: "axolotl.mcvox" },
  { id: "minecraft:bee", name: "蜜蜂", category: "passive", file: "bee.mcvox" },
  { id: "minecraft:sheep", name: "绵羊", category: "passive", file: "sheep.mcvox" },
  { id: "minecraft:ender_dragon", name: "末影龙", category: "hostile", file: "ender_dragon.mcvox" },
  { id: "minecraft:endermite", name: "末影螨", category: "hostile", file: "endermite.mcvox" },
  { id: "minecraft:enderman", name: "末影人", category: "hostile", file: "enderman.mcvox" },
  { id: "minecraft:mooshroom", name: "哞菇", category: "passive", file: "mooshroom.mcvox" },
  { id: "minecraft:vex", name: "恼鬼", category: "hostile", file: "vex.mcvox" },
  { id: "minecraft:drowned", name: "溺尸", category: "hostile", file: "drowned.mcvox" },
  { id: "minecraft:cow", name: "牛", category: "passive", file: "cow.mcvox" },
  { id: "minecraft:witch", name: "女巫", category: "hostile", file: "witch.mcvox" },
  { id: "minecraft:shulker", name: "潜影贝", category: "hostile", file: "shulker.mcvox" },
  { id: "minecraft:frog", name: "青蛙", category: "passive", file: "frog.mcvox" },
  { id: "minecraft:armadillo", name: "犰狳", category: "passive", file: "armadillo.mcvox" },
  { id: "minecraft:tropical_fish", name: "热带鱼", category: "water", file: "tropical_fish.mcvox" },
  { id: "minecraft:goat", name: "山羊", category: "passive", file: "goat.mcvox" },
  { id: "minecraft:husk", name: "尸壳", category: "hostile", file: "husk.mcvox" },
  { id: "minecraft:slime", name: "史莱姆", category: "hostile", file: "slime.mcvox" },
  { id: "minecraft:guardian", name: "守卫者", category: "hostile", file: "guardian.mcvox" },
  { id: "minecraft:iron_golem", name: "铁傀儡", category: "passive", file: "iron_golem.mcvox" },
  { id: "minecraft:rabbit", name: "兔子", category: "passive", file: "rabbit.mcvox" },
  { id: "minecraft:vindicator", name: "卫道士", category: "hostile", file: "vindicator.mcvox" },
  { id: "minecraft:trader_llama", name: "行商羊驼", category: "passive", file: "trader_llama.mcvox" },
  { id: "minecraft:panda", name: "熊猫", category: "passive", file: "panda.mcvox" },
  { id: "minecraft:sniffer", name: "嗅探兽", category: "passive", file: "sniffer.mcvox" },
  { id: "minecraft:breeze", name: "旋风人", category: "hostile", file: "breeze.mcvox" },
  { id: "minecraft:snow_golem", name: "雪傀儡", category: "passive", file: "snow_golem.mcvox" },
  { id: "minecraft:cod", name: "鳕鱼", category: "water", file: "cod.mcvox" },
  { id: "minecraft:magma_cube", name: "岩浆怪", category: "hostile", file: "magma_cube.mcvox" },
  { id: "minecraft:llama", name: "羊驼", category: "passive", file: "llama.mcvox" },
  { id: "minecraft:parrot", name: "鹦鹉", category: "passive", file: "parrot.mcvox" },
  { id: "minecraft:hoglin", name: "疣猪兽", category: "hostile", file: "hoglin.mcvox" },
  { id: "minecraft:squid", name: "鱿鱼", category: "water", file: "squid.mcvox" },
  { id: "minecraft:elder_guardian", name: "远古守卫者", category: "hostile", file: "elder_guardian.mcvox" },
  { id: "minecraft:allay", name: "悦灵", category: "passive", file: "allay.mcvox" },
  { id: "minecraft:bogged", name: "沼骸", category: "hostile", file: "bogged.mcvox" },
  { id: "minecraft:spider", name: "蜘蛛", category: "hostile", file: "spider.mcvox" },
  { id: "minecraft:pig", name: "猪", category: "passive", file: "pig.mcvox" },
  { id: "minecraft:piglin", name: "猪灵", category: "hostile", file: "piglin.mcvox" },
  { id: "minecraft:piglin_brute", name: "猪灵蛮兵", category: "hostile", file: "piglin_brute.mcvox" },
];

const BASE = import.meta.env?.BASE_URL ?? "/";

/** Served URL of a built-in capture. */
export function mobUrl(file: string): string {
  return `${BASE}mobs/${file}`;
}
